name: SkibidiNick
version: 1.0
main: com.deyo.skibidinick.skibidinick
api-version: 1.13
commands:
  nick:
    description: Set a nickname
    usage: /<command>
    permission: skibidinick.nick
  unnick:
    description: Remove your nickname
    usage: /<command>
    permission: skibidinick.unnick
  realname:
    description: Get the real name of a player
    usage: /<command> <nickname>
    permission: skibidinick.realname

permissions:
  skibidinick.nick:
    description: Allows players to use the nick command and GUI
    default: op
  skibidinick.unnick:
    description: Allows players to remove their nickname
    default: op
  skibidinick.realname:
    description: Allows players to check the real name of nicked players
    default: op
